export {default as Logo} from './logo'
export {default as Payment} from './Payment'
export {default as Transport} from './Transport'
export {default as ChooseDestination} from './ChooseDestination'
export {default as Logo2} from './Logo2'
export {default as Twitter } from './Twitter'
export {default as Facebook } from './Facebook'
export {default as Instagram } from './Instagram'
export {default as Hamburger } from './Hamburger'