export {default as NavBar} from './navbar.jsx';
export {default as Hero} from './hero.jsx';
export {default as Section} from './Section'
export {default as Category} from './Category'
export {default as Destination} from './Destination'
export {default as BookCard} from './BookCard'
export {default as Testimonials} from './Testimonials'
export {default as CompanyCarousel} from './Companycarousel'
export {default as Subscribe} from './Subscribe'
export {default as Footer} from './Footer'
export {default as TripStep} from './TripStep'